version: "2"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345
  mongodb:
    image: mvertes/alpine-mongo
  sut:
    build: .
    links:
      - mysql
      - mongodb
    volumes:
      - ./src:/srv/src
      - ./test:/srv/test
    command: test
