version: "2"
services:
  mysql:
    image: imega/mysql
  mongodb:
    image: mvertes/alpine-mongo
  postgres:
    image: postgres
  sut:
    build: .
    links:
      - mysql
      - mongodb
      - postgres
    volumes:
      - ./src:/srv/src
      - ./test:/srv/test
    command: test
